package cz.uhk.macroflow.training.exercises

import cz.uhk.macroflow.training.body.Muscle
import cz.uhk.macroflow.training.body.Muscle.*

/**
 * Atlas svalů a knihovna cviků (čistý Kotlin, pokryto testy). Podklady v docs/adr/0019.
 *
 * Anatomické názvy podle Terminologia Anatomica (latinsky, „m.“ = musculus, „mm.“ = musculi).
 * Technika je psaná pro běžného návštěvníka posilovny – bezpečná výchozí varianta cviku.
 */
enum class Equipment(val label: String) {
    BARBELL("osa"), DUMBBELL("jednoručky"), CABLE("kladka"), MACHINE("stroj"),
    BODYWEIGHT("vlastní váha"), BAR("hrazda / bradla"), OTHER("jiné")
}

data class Exercise(
    val id: String,
    val name: String,
    /** Běžný (často anglický) název, pod kterým cvik lidé znají. */
    val alias: String,
    val equipment: Equipment,
    /** 1 = začátečník, 2 = mírně pokročilý, 3 = pokročilý. */
    val level: Int,
    val primary: Set<Muscle>,
    val secondary: Set<Muscle>,
    val latinPrimary: List<String>,
    val latinSecondary: List<String>,
    val steps: List<String>,
    val tips: List<String>,
    val mistakes: List<String>
) {
    val levelLabel: String get() = when (level) { 1 -> "začátečník"; 2 -> "mírně pokročilý"; else -> "pokročilý" }
    fun works(m: Muscle) = m in primary || m in secondary
}

object MuscleAnatomy {
    /** Latinské názvy svalů, které tvoří danou partii. */
    val LATIN: Map<Muscle, List<String>> = mapOf(
        CHEST to listOf("m. pectoralis major (pars clavicularis, sternocostalis, abdominalis)", "m. pectoralis minor"),
        FRONT_DELTS to listOf("m. deltoideus – pars clavicularis (přední snopec)", "m. deltoideus – pars acromialis (boční snopec)"),
        REAR_DELTS to listOf("m. deltoideus – pars spinalis (zadní snopec)", "m. infraspinatus", "m. teres minor"),
        BICEPS to listOf("m. biceps brachii (caput longum, caput breve)", "m. brachialis", "m. brachioradialis"),
        TRICEPS to listOf("m. triceps brachii (caput longum, laterale, mediale)", "m. anconeus"),
        FOREARMS to listOf("m. flexor carpi radialis", "m. flexor carpi ulnaris", "m. flexor digitorum superficialis et profundus",
            "m. extensor carpi radialis longus et brevis", "m. extensor carpi ulnaris", "m. brachioradialis"),
        ABS to listOf("m. rectus abdominis", "m. transversus abdominis"),
        OBLIQUES to listOf("m. obliquus externus abdominis", "m. obliquus internus abdominis"),
        TRAPS to listOf("m. trapezius (pars descendens, transversa, ascendens)", "m. levator scapulae", "mm. rhomboidei (major, minor)"),
        LATS to listOf("m. latissimus dorsi", "m. teres major"),
        LOWER_BACK to listOf("m. erector spinae (m. iliocostalis, m. longissimus, m. spinalis)", "m. quadratus lumborum", "mm. multifidi"),
        GLUTES to listOf("m. gluteus maximus", "m. gluteus medius", "m. gluteus minimus"),
        QUADS to listOf("m. quadriceps femoris: m. rectus femoris", "m. vastus lateralis", "m. vastus medialis", "m. vastus intermedius"),
        HAMSTRINGS to listOf("m. biceps femoris (caput longum, caput breve)", "m. semitendinosus", "m. semimembranosus"),
        CALVES to listOf("m. gastrocnemius (caput mediale, caput laterale)", "m. soleus")
    )

    /** Krátký popis funkce partie (co sval dělá). */
    val FUNCTION: Map<Muscle, String> = mapOf(
        CHEST to "Přitahuje paži k tělu a před tělo (horizontální addukce), tlačí vpřed.",
        FRONT_DELTS to "Zvedá paži vpřed a do strany, spolupracuje při tlaku nad hlavu.",
        REAR_DELTS to "Táhne paži vzad, rotuje rameno zevně – zdraví a držení ramen.",
        BICEPS to "Ohýbá loket a otáčí předloktí dlaní vzhůru (supinace).",
        TRICEPS to "Propíná loket; dlouhá hlava pomáhá táhnout paži dolů a vzad.",
        FOREARMS to "Ohýbají a propínají zápěstí a prsty – úchop.",
        ABS to "Ohýbá trup vpřed a zpevňuje ho proti prohnutí; příčný sval stahuje břicho.",
        OBLIQUES to "Rotují a uklánějí trup, brání nechtěné rotaci.",
        TRAPS to "Zvedají, přitahují a stabilizují lopatky.",
        LATS to "Táhnou paži dolů a k tělu – shyby, přítahy.",
        LOWER_BACK to "Narovnávají a drží páteř v neutrální poloze.",
        GLUTES to "Propínají kyčel (vzpřímení z předklonu, výskok) a stabilizují pánev.",
        QUADS to "Propínají koleno, přímý sval pomáhá ohýbat kyčel.",
        HAMSTRINGS to "Ohýbají koleno a propínají kyčel.",
        CALVES to "Propínají kotník (výpon); lýtkový sval při propnutém, šíjový při pokrčeném koleni."
    )
}

object ExerciseLibrary {

    private fun ex(
        id: String, name: String, alias: String, eq: Equipment, level: Int,
        primary: Set<Muscle>, secondary: Set<Muscle>,
        latinPrimary: List<String>, latinSecondary: List<String>,
        steps: List<String>, tips: List<String>, mistakes: List<String>
    ) = Exercise(id, name, alias, eq, level, primary, secondary, latinPrimary, latinSecondary, steps, tips, mistakes)

    val ALL: List<Exercise> = listOf(
        // ═══ PRSA ═══
        ex("bench_press", "Tlak na rovné lavici", "Bench press", Equipment.BARBELL, 2,
            setOf(CHEST), setOf(FRONT_DELTS, TRICEPS),
            listOf("m. pectoralis major (pars sternocostalis)"),
            listOf("m. deltoideus (pars clavicularis)", "m. triceps brachii", "m. serratus anterior"),
            listOf("Lehni si tak, aby oči byly pod osou. Chodidla pevně na zemi, lopatky stáhni k sobě a dolů.",
                "Uchop osu o něco šířeji než ramena, zápěstí rovně nad lokty.",
                "Sundej osu, s nádechem ji pomalu spusť na spodní část hrudníku, lokty asi 45–70° od těla.",
                "S výdechem tlač osu nahoru a mírně k hlavě, dokud nepropneš lokty."),
            listOf("Lopatky drž stažené celou sérii – ramena zůstanou v bezpečí.", "Těžké série jen s dopomocí nebo v kleci s bezpečnostními zarážkami."),
            listOf("Odrážení osy od hrudníku.", "Lokty roztažené do 90° – zbytečně zatěžuje ramenní kloub.")),
        ex("incline_db_press", "Tlak jednoruček na šikmé lavici", "Incline dumbbell press", Equipment.DUMBBELL, 2,
            setOf(CHEST), setOf(FRONT_DELTS, TRICEPS),
            listOf("m. pectoralis major (pars clavicularis)"),
            listOf("m. deltoideus (pars clavicularis)", "m. triceps brachii"),
            listOf("Nastav lavici na 30–45°. Sedni si s jednoručkami na stehnech a opatrně si lehni.",
                "Jednoručky nad hrudníkem, dlaně směřují k nohám, lopatky stažené.",
                "Pomalu spouštěj do úrovně horního hrudníku, lokty mírně pod úrovní ramen.",
                "Vytlač nahoru a lehce k sobě, nahoře se jednoručky skoro dotknou."),
            listOf("Menší sklon (30°) cílí víc na prsa, větší víc na ramena.", "Plný rozsah dolů – protažení prsního svalu je pro růst výhodné."),
            listOf("Příliš strmá lavice – z cviku se stane tlak na ramena.", "Ťukání jednoruček nahoře a ztráta napětí.")),
        ex("chest_dip", "Kliky na bradlech s předklonem", "Chest dips", Equipment.BAR, 3,
            setOf(CHEST, TRICEPS), setOf(FRONT_DELTS),
            listOf("m. pectoralis major (pars sternocostalis, pars abdominalis)", "m. triceps brachii"),
            listOf("m. deltoideus (pars clavicularis)", "m. pectoralis minor"),
            listOf("Vzepři se na bradlech s propnutými lokty.",
                "Nakloň trup mírně vpřed, nohy pokrč za tělem.",
                "Pomalu se spouštěj, dokud nejsou ramena lehce pod úrovní loktů (pokud to ramena snesou).",
                "Vytlač se zpět nahoru, lokty mírně od těla."),
            listOf("Předklon víc zapojí prsa, vzpřímený trup víc triceps.", "Začni s dopomocí (guma, stroj), dokud nezvládneš 8 čistých opakování."),
            listOf("Příliš hluboké spouštění při bolesti ramen.", "Houpání nohama a švih.")),
        ex("cable_fly", "Rozpažování na kladkách", "Cable fly", Equipment.CABLE, 1,
            setOf(CHEST), setOf(FRONT_DELTS),
            listOf("m. pectoralis major"),
            listOf("m. deltoideus (pars clavicularis)", "m. biceps brachii (stabilizace lokte)"),
            listOf("Kladky nastav do výšky ramen, uchop madla a udělej krok vpřed do mírného výpadu.",
                "Lokty lehce pokrčené a v té pozici zamčené po celou dobu.",
                "Obloukem přitáhni madla před hrudník, jako bys objímal strom.",
                "Pomalu se vrať do roztažení, dokud cítíš protažení prsou."),
            listOf("Myšlenka „přitáhnout paže k sobě“, ne „tlačit“.", "Horní kladky = spodní prsa, spodní kladky = horní prsa."),
            listOf("Ohýbání a propínání loktů – z rozpažování se stane tlak.", "Příliš velká váha a trhání.")),
        ex("push_up", "Klik", "Push-up", Equipment.BODYWEIGHT, 1,
            setOf(CHEST), setOf(TRICEPS, FRONT_DELTS, ABS),
            listOf("m. pectoralis major"),
            listOf("m. triceps brachii", "m. deltoideus (pars clavicularis)", "m. serratus anterior", "m. rectus abdominis (zpevnění)"),
            listOf("Dlaně o něco šířeji než ramena, tělo v jedné linii od hlavy po paty.",
                "Zpevni břicho a hýždě.",
                "Spusť se, dokud se hrudník skoro nedotkne země, lokty asi 45° od těla.",
                "Vytlač se nahoru do propnutých paží, nahoře lopatky lehce rozevři."),
            listOf("Ztížení: nohy na lavici nebo zátěž na zádech. Usnadnění: ruce na lavici.", "Tempo 2 s dolů, 1 s nahoru."),
            listOf("Propadlá bedra (prohnutí).", "Zvednutý zadek a zkrácený pohyb.")),

        // ═══ RAMENA (PŘEDNÍ A BOČNÍ SNOPEC) ═══
        ex("overhead_press", "Tlak nad hlavu vestoje", "Overhead press", Equipment.BARBELL, 2,
            setOf(FRONT_DELTS), setOf(TRICEPS, TRAPS, ABS),
            listOf("m. deltoideus (pars clavicularis, pars acromialis)"),
            listOf("m. triceps brachii", "m. trapezius (pars descendens)", "m. serratus anterior", "m. rectus abdominis"),
            listOf("Osa leží na předních ramenou, úchop těsně vně ramen, lokty lehce před osou.",
                "Zpevni hýždě a břicho, nohy na šířku pánve.",
                "Tlač osu svisle nahoru, hlavu na okamžik stáhni vzad, aby osa prošla.",
                "Nahoře dostaň hlavu „do okna“ pod osu, pak pomalu zpět na ramena."),
            listOf("Osa má jít po přímce nad středem chodidla.", "Nádech a zpevnění před každým opakováním."),
            listOf("Záklon a přetížení beder.", "Tlačení osy před obličej místo nad hlavu.")),
        ex("db_shoulder_press", "Tlak jednoruček vsedě", "Seated dumbbell press", Equipment.DUMBBELL, 1,
            setOf(FRONT_DELTS), setOf(TRICEPS, TRAPS),
            listOf("m. deltoideus (pars clavicularis, pars acromialis)"),
            listOf("m. triceps brachii", "m. trapezius", "m. serratus anterior"),
            listOf("Opěrka lavice skoro svisle (75–90°), záda opřená.",
                "Jednoručky u ramen, dlaně vpřed nebo mírně k sobě, lokty lehce před tělem.",
                "Vytlač nahoru, dokud se lokty téměř nepropnou.",
                "Pomalu spouštěj do úrovně brady až uší."),
            listOf("Neutrální úchop (dlaně k sobě) bývá šetrnější k ramenům.", "Lopatky opřené o lavici."),
            listOf("Odlepení zad a prohnutí.", "Příliš krátký pohyb dolů.")),
        ex("lateral_raise", "Upažování s jednoručkami", "Lateral raise", Equipment.DUMBBELL, 1,
            setOf(FRONT_DELTS), setOf(TRAPS),
            listOf("m. deltoideus (pars acromialis)"),
            listOf("m. supraspinatus", "m. trapezius (pars descendens)"),
            listOf("Stoj, jednoručky podél těla, lehký předklon trupu.",
                "Lokty mírně pokrčené, vedou pohyb.",
                "Zvedej paže do strany do výšky ramen, malíček nesmí být výš než palec.",
                "Pomalu spouštěj zpět, bez odpočinku dole."),
            listOf("Menší váha, víc opakování (12–20) – boční snopec má rád objem.", "Představ si, že paže „vytahuješ do dálky“."),
            listOf("Švih celým tělem.", "Krčení ramen k uším – přebírají práci trapézy.")),
        ex("front_raise", "Předpažování", "Front raise", Equipment.DUMBBELL, 1,
            setOf(FRONT_DELTS), setOf(CHEST),
            listOf("m. deltoideus (pars clavicularis)"),
            listOf("m. pectoralis major (pars clavicularis)", "m. serratus anterior"),
            listOf("Stoj, jednoručky před stehny, dlaně k tělu.",
                "Zpevni trup a zvedej paži vpřed do výšky očí.",
                "Krátká pauza nahoře, pak pomalu dolů.",
                "Střídej paže nebo zvedej obě najednou."),
            listOf("Přední snopec dostává hodně práce už z tlaků – stačí málo sérií.", "Palce mírně nahoru je šetrnější k ramenu."),
            listOf("Záklon a švih.", "Zvedání nad hlavu – zbytečné.")),

        // ═══ ZADNÍ RAMENA ═══
        ex("face_pull", "Přítah lana k obličeji", "Face pull", Equipment.CABLE, 1,
            setOf(REAR_DELTS), setOf(TRAPS),
            listOf("m. deltoideus (pars spinalis)", "m. infraspinatus", "m. teres minor"),
            listOf("m. trapezius (pars transversa, ascendens)", "mm. rhomboidei"),
            listOf("Kladka ve výšce obličeje, uchop lano nadhmatem (palce k sobě).",
                "Ustup, aby bylo lano napnuté, trup vzpřímený.",
                "Táhni lano k obličeji, lokty vysoko a do stran, konce lana roztáhni k uším.",
                "Na konci vytoč ruce vzad (jako „dvojitý biceps“), pomalu zpět."),
            listOf("Skvělý doplněk k tlakům pro zdravá ramena.", "Lehčí váha, důraz na vytočení na konci."),
            listOf("Tahání za pomoci záklonu.", "Lokty dole – cvik se změní na přítah.")),
        ex("reverse_fly", "Zapažování v předklonu", "Rear delt fly", Equipment.DUMBBELL, 1,
            setOf(REAR_DELTS), setOf(TRAPS),
            listOf("m. deltoideus (pars spinalis)"),
            listOf("m. infraspinatus", "m. teres minor", "m. trapezius (pars transversa)", "mm. rhomboidei"),
            listOf("Předkloň se v kyčlích skoro do vodorovné polohy (nebo si lehni čelem na šikmou lavici).",
                "Jednoručky visí pod rameny, lokty lehce pokrčené.",
                "Roztáhni paže do stran, dokud nejsou v linii s tělem.",
                "Pomalu zpět dolů."),
            listOf("Mysli na to, že ruce „odhazuješ do stran“, ne dozadu.", "Opora hrudníku o lavici odstraní švih."),
            listOf("Stahování lopatek – práci převezmou rombické svaly.", "Příliš těžké jednoručky.")),

        // ═══ BICEPS ═══
        ex("barbell_curl", "Bicepsový zdvih s osou", "Barbell curl", Equipment.BARBELL, 1,
            setOf(BICEPS), setOf(FOREARMS),
            listOf("m. biceps brachii", "m. brachialis"),
            listOf("m. brachioradialis", "flexory předloktí"),
            listOf("Stoj, osa v podhmatu na šířku ramen, lokty u těla.",
                "Bez pohybu loktů zvedej osu obloukem k ramenům.",
                "Nahoře krátce zatni biceps.",
                "Pomalu spouštěj až do propnutí loktů."),
            listOf("Plný rozsah dolů je důležitější než těžká váha.", "EZ osa ulehčí zápěstím."),
            listOf("Švih trupem.", "Lokty jedou dopředu – zapojují se ramena.")),
        ex("incline_db_curl", "Zdvih jednoruček na šikmé lavici", "Incline dumbbell curl", Equipment.DUMBBELL, 2,
            setOf(BICEPS), setOf(FOREARMS),
            listOf("m. biceps brachii (caput longum)"),
            listOf("m. brachialis", "m. brachioradialis"),
            listOf("Lavice na 45–60°, lehni si, paže visí volně za tělem.",
                "Dlaně vpřed, lokty zůstávají pod rameny.",
                "Zvedej jednoručky k ramenům bez posunu loktů.",
                "Pomalu spouštěj do plného protažení."),
            listOf("Paže za tělem protahují dlouhou hlavu bicepsu.", "Lehčí váha než vestoje."),
            listOf("Zvedání loktů vpřed.", "Zkrácený rozsah dole.")),
        ex("hammer_curl", "Kladivový zdvih", "Hammer curl", Equipment.DUMBBELL, 1,
            setOf(BICEPS, FOREARMS), emptySet(),
            listOf("m. brachialis", "m. brachioradialis"),
            listOf("m. biceps brachii"),
            listOf("Stoj, jednoručky podél těla, dlaně k sobě (neutrální úchop).",
                "Lokty u těla, zvedej jednoručku k rameni.",
                "Palec míří nahoru po celou dobu.",
                "Pomalu dolů."),
            listOf("Buduje tloušťku paže a sílu úchopu.", "Lze střídavě i najednou."),
            listOf("Švih.", "Otáčení zápěstí.")),

        // ═══ TRICEPS ═══
        ex("close_grip_bench", "Tlak na lavici úzkým úchopem", "Close-grip bench press", Equipment.BARBELL, 2,
            setOf(TRICEPS), setOf(CHEST, FRONT_DELTS),
            listOf("m. triceps brachii"),
            listOf("m. pectoralis major", "m. deltoideus (pars clavicularis)"),
            listOf("Lehni jako na bench, úchop na šířku ramen (ne užší).",
                "Lopatky stažené, lokty blízko těla.",
                "Spusť osu na spodní hrudník.",
                "Vytlač nahoru do propnutí loktů."),
            listOf("Příliš úzký úchop přetěžuje zápěstí.", "Skvělý těžký základ pro triceps."),
            listOf("Lokty roztažené do stran.", "Odrážení od hrudníku.")),
        ex("triceps_pushdown", "Stahování kladky na triceps", "Triceps pushdown", Equipment.CABLE, 1,
            setOf(TRICEPS), emptySet(),
            listOf("m. triceps brachii (caput laterale, caput mediale)"),
            listOf("m. anconeus"),
            listOf("Horní kladka, rovná tyč nebo lano, stoj blízko kladky.",
                "Lokty přitiskni k tělu a nech je na místě.",
                "Propni lokty a tlač dolů, s lanem konce na konci roztáhni.",
                "Pomalu zpět, dokud předloktí nejsou nad vodorovnou."),
            listOf("Mírný předklon trupu je v pořádku.", "Lano dovolí dotáhnout pohyb víc."),
            listOf("Lokty jezdí vpřed a vzad.", "Přetlačování celým tělem.")),
        ex("overhead_extension", "Tricepsový tlak nad hlavou", "Overhead triceps extension", Equipment.CABLE, 1,
            setOf(TRICEPS), emptySet(),
            listOf("m. triceps brachii (caput longum)"),
            listOf("m. triceps brachii (caput laterale, caput mediale)"),
            listOf("Otoč se zády ke kladce, lano drž za hlavou, lokty míří vpřed a nahoru.",
                "Udělej krok vpřed do mírného výpadu, trup zpevni.",
                "Propni lokty a vytlač lano vpřed nad hlavu.",
                "Pomalu zpět do hlubokého protažení za hlavou."),
            listOf("Paže nad hlavou protahují dlouhou hlavu – roste víc než při stahování dolů.", "Jde i s jednoručkou oběma rukama."),
            listOf("Roztahování loktů do stran.", "Prohnutí v bedrech.")),
        ex("skull_crusher", "Francouzský tlak vleže", "Skull crusher", Equipment.BARBELL, 2,
            setOf(TRICEPS), emptySet(),
            listOf("m. triceps brachii"),
            listOf("m. anconeus"),
            listOf("Lehni na lavici, EZ osa nad hrudníkem v nadhmatu na šířku ramen.",
                "Nakloň paže mírně za hlavu (ne svisle).",
                "Ohýbej lokty a spouštěj osu za temeno hlavy.",
                "Propni lokty zpět do výchozí polohy."),
            listOf("Paže lehce za hlavou udrží napětí celou dobu.", "Začni lehce – lokty to ocení."),
            listOf("Lokty do stran.", "Pohyb v ramenou místo v loktech.")),

        // ═══ PŘEDLOKTÍ ═══
        ex("wrist_curl", "Zápěstní flexe", "Wrist curl", Equipment.BARBELL, 1,
            setOf(FOREARMS), emptySet(),
            listOf("m. flexor carpi radialis", "m. flexor carpi ulnaris", "m. flexor digitorum superficialis et profundus"),
            listOf("m. palmaris longus"),
            listOf("Sedni si, předloktí polož na stehna, dlaně vzhůru, zápěstí přes kolena.",
                "Nech osu sjet do prstů.",
                "Sevři prsty a ohni zápěstí nahoru.",
                "Pomalu zpět."),
            listOf("Vyšší počet opakování (15–25).", "Plný rozsah i do prstů."),
            listOf("Zvedání předloktí ze stehen.", "Rychlé cukání.")),
        ex("reverse_wrist_curl", "Zápěstní extenze", "Reverse wrist curl", Equipment.DUMBBELL, 1,
            setOf(FOREARMS), emptySet(),
            listOf("m. extensor carpi radialis longus et brevis", "m. extensor carpi ulnaris"),
            listOf("m. extensor digitorum"),
            listOf("Předloktí na stehnech, dlaně dolů, zápěstí přes kolena.",
                "Zvedej hřbet ruky nahoru.",
                "Krátká pauza nahoře.",
                "Pomalu dolů."),
            listOf("Vyvažuje flexory – prevence „tenisového lokte“.", "Stačí malá váha."),
            listOf("Moc velká zátěž a švih.", "Pohyb z lokte.")),
        ex("farmers_walk", "Farmářská chůze", "Farmer's walk", Equipment.DUMBBELL, 1,
            setOf(FOREARMS, TRAPS), setOf(ABS, OBLIQUES, GLUTES),
            listOf("mm. flexores digitorum et carpi", "m. trapezius (pars descendens)"),
            listOf("m. quadratus lumborum", "mm. obliqui abdominis", "m. gluteus medius"),
            listOf("Zvedni těžké jednoručky (nebo kettlebelly) jako při mrtvém tahu.",
                "Vzpřim se, ramena dolů a vzad, břicho zpevněné.",
                "Jdi krátkými rychlými kroky 20–40 m.",
                "Polož zátěž se stejnou technikou jako při zvedání."),
            listOf("Úchop, trapézy i střed těla najednou.", "Dívej se před sebe, ne pod nohy."),
            listOf("Kulatá záda při zvedání.", "Naklánění do strany.")),

        // ═══ BŘICHO ═══
        ex("plank", "Prkno", "Plank", Equipment.BODYWEIGHT, 1,
            setOf(ABS), setOf(OBLIQUES, GLUTES),
            listOf("m. transversus abdominis", "m. rectus abdominis"),
            listOf("mm. obliqui abdominis", "m. gluteus maximus", "m. serratus anterior"),
            listOf("Opři se o předloktí a špičky, lokty pod rameny.",
                "Tělo v jedné přímce od hlavy po paty.",
                "Zatni hýždě a „přitáhni pupík k páteři“.",
                "Drž 20–60 s a klidně dýchej."),
            listOf("Kvalita před délkou – raději 3× 30 s pořádně.", "Ztížení: zvedni jednu ruku nebo nohu."),
            listOf("Propadlá bedra.", "Zadek vysoko nahoře.")),
        ex("hanging_leg_raise", "Zvedání nohou ve visu", "Hanging leg raise", Equipment.BAR, 3,
            setOf(ABS), setOf(OBLIQUES),
            listOf("m. rectus abdominis (hlavně spodní část)", "m. iliopsoas"),
            listOf("mm. obliqui abdominis", "m. rectus femoris"),
            listOf("Vis na hrazdě nadhmatem, ramena aktivní (ne úplně prověšená).",
                "Zastav houpání, zpevni břicho.",
                "Zvedni pokrčená (nebo propnutá) kolena k hrudníku a podsaď pánev.",
                "Pomalu spouštěj bez švihu."),
            listOf("Podsazení pánve nahoře = práce břicha, ne jen ohybačů kyčle.", "Začni s pokrčenými koleny."),
            listOf("Houpání tělem.", "Jen zvednutí nohou bez podsazení pánve.")),
        ex("cable_crunch", "Zkracovačky na kladce", "Cable crunch", Equipment.CABLE, 1,
            setOf(ABS), emptySet(),
            listOf("m. rectus abdominis"),
            listOf("mm. obliqui abdominis"),
            listOf("Klekni před horní kladku, lano drž u hlavy.",
                "Boky zůstávají na místě.",
                "Stoč trup dolů – žebra k pánvi, loktem k polovině stehen.",
                "Pomalu se rozviň zpět nahoru."),
            listOf("Pohyb dělá páteř, ne kyčle.", "Břicho se dá zatížit jako každý jiný sval – 8–15 opakování."),
            listOf("Sedání na paty a tahání rukama.", "Zaokrouhlení jen krku.")),
        ex("ab_wheel", "Kolečko na břicho", "Ab wheel rollout", Equipment.OTHER, 3,
            setOf(ABS), setOf(LATS, OBLIQUES),
            listOf("m. rectus abdominis", "m. transversus abdominis"),
            listOf("m. latissimus dorsi", "mm. obliqui abdominis"),
            listOf("Klekni, kolečko pod rameny, podsaď pánev.",
                "Pomalu jeď vpřed, dokud udržíš bedra rovná.",
                "Břicho brání prohnutí.",
                "Přitáhni se zpět silou břicha."),
            listOf("Začni s krátkým rozsahem, prodlužuj postupně.", "Proti zdi se dá rozsah omezit."),
            listOf("Prohnutí v bedrech.", "Příliš dlouhý rozsah hned na začátku.")),

        // ═══ ŠIKMÉ BŘIŠNÍ ═══
        ex("pallof_press", "Pallofův tlak", "Pallof press", Equipment.CABLE, 1,
            setOf(OBLIQUES), setOf(ABS),
            listOf("m. obliquus externus abdominis", "m. obliquus internus abdominis"),
            listOf("m. transversus abdominis", "m. rectus abdominis"),
            listOf("Kladka ve výšce hrudníku, stoupni si bokem, madlo oběma rukama u hrudníku.",
                "Odstup, aby lano táhlo do strany.",
                "Vytlač ruce vpřed a nedovol trupu se natočit.",
                "Vydrž 2 s, vrať ruce k hrudníku."),
            listOf("Cvik proti rotaci – střed těla se učí nepovolit.", "Obě strany stejně."),
            listOf("Natočení trupu ke kladce.", "Zadržený dech.")),
        ex("side_plank", "Boční prkno", "Side plank", Equipment.BODYWEIGHT, 1,
            setOf(OBLIQUES), setOf(GLUTES, ABS),
            listOf("mm. obliqui abdominis", "m. quadratus lumborum"),
            listOf("m. gluteus medius", "m. transversus abdominis"),
            listOf("Lehni na bok, loket pod ramenem, nohy nad sebou.",
                "Zvedni boky, tělo v přímce.",
                "Drž 20–45 s.",
                "Vyměň stranu."),
            listOf("Ztížení: horní nohu zvedni.", "Usnadnění: opři kolena."),
            listOf("Klesající boky.", "Předklon trupu.")),
        ex("woodchop", "Sekání dřeva na kladce", "Cable woodchop", Equipment.CABLE, 2,
            setOf(OBLIQUES), setOf(ABS, FRONT_DELTS),
            listOf("m. obliquus externus abdominis", "m. obliquus internus abdominis"),
            listOf("m. rectus abdominis", "m. deltoideus"),
            listOf("Kladka nahoře, bokem, uchop madlo oběma rukama.",
                "Paže propnuté, táhni šikmo dolů přes tělo k opačnému koleni.",
                "Rotace vychází z trupu a boků.",
                "Kontrolovaně zpět."),
            listOf("Plynulé, ne trhavé.", "Opačný směr (zdola nahoru) je stejně dobrý."),
            listOf("Tahání rukama.", "Kulatá záda.")),

        // ═══ TRAPÉZY ═══
        ex("shrug", "Krčení ramen", "Shrug", Equipment.DUMBBELL, 1,
            setOf(TRAPS), setOf(FOREARMS),
            listOf("m. trapezius (pars descendens)", "m. levator scapulae"),
            listOf("flexory prstů (úchop)"),
            listOf("Stoj, těžké jednoručky podél těla.",
                "Zvedni ramena přímo nahoru k uším.",
                "Nahoře vydrž 1–2 s.",
                "Pomalu spusť do plného protažení."),
            listOf("Svisle nahoru, žádné kroužení.", "Popruhy pomohou, když selhává úchop."),
            listOf("Kroužení ramen.", "Ohýbání loktů.")),

        // ═══ ŠIROKÝ ZÁDOVÝ ═══
        ex("pull_up", "Shyby nadhmatem", "Pull-up", Equipment.BAR, 3,
            setOf(LATS), setOf(BICEPS, REAR_DELTS, TRAPS),
            listOf("m. latissimus dorsi", "m. teres major"),
            listOf("m. biceps brachii", "m. brachialis", "m. trapezius (pars ascendens)", "mm. rhomboidei"),
            listOf("Vis na hrazdě nadhmatem o něco šířeji než ramena.",
                "Nejdřív stáhni lopatky dolů.",
                "Přitáhni se, dokud brada není nad hrazdou, lokty míří k bokům.",
                "Pomalu se spusť do plného visu."),
            listOf("Negativní shyby nebo guma, dokud nezvládneš 5 čistých.", "Mysli na „lokty do kapes“."),
            listOf("Švih a kopání nohama.", "Poloviční rozsah.")),
        ex("chin_up", "Shyby podhmatem", "Chin-up", Equipment.BAR, 2,
            setOf(LATS, BICEPS), setOf(TRAPS),
            listOf("m. latissimus dorsi", "m. biceps brachii"),
            listOf("m. brachialis", "m. teres major", "mm. rhomboidei"),
            listOf("Vis podhmatem na šířku ramen.",
                "Stáhni lopatky dolů.",
                "Přitáhni hrudník k hrazdě.",
                "Pomalu dolů do plného visu."),
            listOf("O něco snazší než nadhmat, víc biceps.", "Plný vis dole."),
            listOf("Kývání.", "Přitahování jen bradou.")),
        ex("lat_pulldown", "Stahování horní kladky", "Lat pulldown", Equipment.CABLE, 1,
            setOf(LATS), setOf(BICEPS, REAR_DELTS),
            listOf("m. latissimus dorsi", "m. teres major"),
            listOf("m. biceps brachii", "m. trapezius (pars ascendens)", "mm. rhomboidei"),
            listOf("Sedni si, stehna pod opěrkou, tyč nadhmatem o něco šířeji než ramena.",
                "Mírný záklon trupu, hrudník nahoru.",
                "Stáhni tyč k hornímu hrudníku, lokty dolů a k tělu.",
                "Pomalu nahoru do plného protažení."),
            listOf("Skvělá cesta k prvnímu shybu.", "Neutrální úchop je šetrnější k ramenům."),
            listOf("Stahování za hlavu.", "Velký záklon a švih.")),
        ex("barbell_row", "Přítah osy v předklonu", "Barbell row", Equipment.BARBELL, 2,
            setOf(LATS, TRAPS), setOf(REAR_DELTS, BICEPS, LOWER_BACK),
            listOf("m. latissimus dorsi", "m. trapezius (pars transversa)", "mm. rhomboidei"),
            listOf("m. deltoideus (pars spinalis)", "m. biceps brachii", "m. erector spinae (izometricky)"),
            listOf("Předkloň se v kyčlích na 30–45° od vodorovné, kolena pokrčená, záda rovná.",
                "Osa visí pod rameny, úchop o něco šířeji než ramena.",
                "Přitáhni osu k pupíku, lokty podél těla.",
                "Pomalu spusť do propnutých paží."),
            listOf("Trup drž na místě – žádné přizvedání.", "Zpevněné břicho chrání bedra."),
            listOf("Kulatá záda.", "Přitahování švihem ze zad.")),
        ex("db_row", "Přítah jednoručky jednoruč", "One-arm dumbbell row", Equipment.DUMBBELL, 1,
            setOf(LATS), setOf(TRAPS, REAR_DELTS, BICEPS),
            listOf("m. latissimus dorsi"),
            listOf("mm. rhomboidei", "m. trapezius (pars transversa)", "m. deltoideus (pars spinalis)", "m. biceps brachii"),
            listOf("Opři koleno a ruku o lavici, záda rovná.",
                "Jednoručka visí pod ramenem.",
                "Táhni loket vzad a nahoru k boku.",
                "Pomalu dolů do protažení."),
            listOf("Tah „k boku“ víc zapojí široký sval.", "Nerotuj trup."),
            listOf("Otáčení trupu.", "Tahání k hrudníku rukou.")),
        ex("straight_arm_pulldown", "Stahování s propnutými pažemi", "Straight-arm pulldown", Equipment.CABLE, 1,
            setOf(LATS), emptySet(),
            listOf("m. latissimus dorsi", "m. teres major"),
            listOf("m. triceps brachii (caput longum)"),
            listOf("Stoj před horní kladkou, rovná tyč nebo lano, mírný předklon.",
                "Paže skoro propnuté, lokty zamčené.",
                "Stáhni tyč obloukem až ke stehnům.",
                "Pomalu zpět nahoru do protažení."),
            listOf("Izoluje široký sval bez bicepsu.", "Dobrý na „nalezení“ zádového svalu."),
            listOf("Ohýbání loktů.", "Kývání trupem.")),

        // ═══ SPODNÍ ZÁDA ═══
        ex("deadlift", "Mrtvý tah", "Deadlift", Equipment.BARBELL, 3,
            setOf(LOWER_BACK, GLUTES, HAMSTRINGS), setOf(QUADS, TRAPS, LATS, FOREARMS),
            listOf("m. erector spinae", "m. gluteus maximus", "m. biceps femoris", "m. semitendinosus", "m. semimembranosus"),
            listOf("m. quadriceps femoris", "m. trapezius", "m. latissimus dorsi", "flexory prstů"),
            listOf("Stoj, osa nad středem chodidla, nohy na šířku pánve.",
                "Předkloň se, uchop osu těsně vně nohou, holeně se dotknou osy.",
                "Hrudník nahoru, záda rovná, napni široký sval („odlomit osu“).",
                "Tlač podlahu nohama, osa jede po nohou nahoru, vzpřim se do stoje a vrať stejnou cestou."),
            listOf("Osa celou dobu u těla.", "Nádech a zpevnění před každým opakováním."),
            listOf("Kulatá záda.", "Záklon nahoře.")),
        ex("back_extension", "Hyperextenze", "Back extension", Equipment.MACHINE, 1,
            setOf(LOWER_BACK), setOf(GLUTES, HAMSTRINGS),
            listOf("m. erector spinae"),
            listOf("m. gluteus maximus", "m. biceps femoris"),
            listOf("Opěrka těsně pod kyčlemi, nohy zapřené.",
                "Ruce na hrudníku nebo za hlavou.",
                "Předkloň se, pak se zvedni do přímky s nohama.",
                "Pomalu dolů."),
            listOf("Nahoře nepřehánět záklon.", "Zátěž: kotouč na hrudníku."),
            listOf("Hyperextenze v bedrech nahoře.", "Švih.")),
        ex("bird_dog", "Bird dog", "Bird dog", Equipment.BODYWEIGHT, 1,
            setOf(LOWER_BACK), setOf(ABS, GLUTES),
            listOf("m. erector spinae", "mm. multifidi"),
            listOf("m. transversus abdominis", "m. gluteus maximus"),
            listOf("Klek na všech čtyřech, dlaně pod rameny, kolena pod kyčlemi.",
                "Zpevni břicho.",
                "Natáhni současně opačnou ruku a nohu do přímky s tělem.",
                "Vydrž 2–3 s, vrať a vyměň strany."),
            listOf("Skvělé na rozcvičku a stabilitu páteře.", "Pomalu, bez houpání pánve."),
            listOf("Prohnutí v bedrech.", "Zvedání nohy příliš vysoko.")),

        // ═══ HÝŽDĚ ═══
        ex("hip_thrust", "Hip thrust", "Hip thrust", Equipment.BARBELL, 2,
            setOf(GLUTES), setOf(HAMSTRINGS, QUADS),
            listOf("m. gluteus maximus"),
            listOf("m. gluteus medius", "m. biceps femoris", "m. quadriceps femoris"),
            listOf("Horní část zad opři o lavici, osa (s podložkou) v přehybu kyčlí.",
                "Chodidla na šířku pánve, holeně nahoře svisle.",
                "Tlač přes paty a zvedni pánev, dokud nejsou trup a stehna v přímce.",
                "Nahoře zatni hýždě, bradu drž u hrudníku, pomalu dolů."),
            listOf("Nahoře podsaď pánev – neprohýbej se.", "Pohled vpřed, ne ke stropu."),
            listOf("Prohnutí v bedrech nahoře.", "Tlak přes špičky.")),
        ex("bulgarian_split_squat", "Bulharský dřep", "Bulgarian split squat", Equipment.DUMBBELL, 2,
            setOf(QUADS, GLUTES), setOf(HAMSTRINGS),
            listOf("m. quadriceps femoris", "m. gluteus maximus"),
            listOf("m. gluteus medius", "m. adductor magnus", "m. biceps femoris"),
            listOf("Zadní nohu polož nártem na lavici, přední asi dva kroky před ní.",
                "Jednoručky podél těla, trup vzpřímený.",
                "Spusť se, dokud zadní koleno skoro nedotkne země.",
                "Vytlač se přední nohou nahoru."),
            listOf("Větší krok a předklon = víc hýždě, kratší krok = víc stehno.", "Stabilita přijde s tréninkem."),
            listOf("Koleno padá dovnitř.", "Odrážení zadní nohou.")),
        ex("hip_abduction", "Unožování na stroji", "Hip abduction", Equipment.MACHINE, 1,
            setOf(GLUTES), emptySet(),
            listOf("m. gluteus medius", "m. gluteus minimus"),
            listOf("m. tensor fasciae latae"),
            listOf("Sedni si do stroje, opěrky vně kolen.",
                "Mírný předklon trupu víc zapojí hýždě.",
                "Roztáhni kolena do stran.",
                "Pomalu zpět."),
            listOf("Střední hýžďový sval stabilizuje pánev při chůzi a dřepu.", "Vyšší počty opakování."),
            listOf("Trhání.", "Příliš malý rozsah.")),

        // ═══ STEHNA – KVADRICEPS ═══
        ex("back_squat", "Dřep s osou na zádech", "Back squat", Equipment.BARBELL, 2,
            setOf(QUADS, GLUTES), setOf(HAMSTRINGS, LOWER_BACK, ABS),
            listOf("m. quadriceps femoris", "m. gluteus maximus"),
            listOf("m. adductor magnus", "m. erector spinae", "m. biceps femoris", "m. rectus abdominis"),
            listOf("Osa na horní části trapézů, úchop pevně, lokty dolů.",
                "Nohy na šířku ramen, špičky mírně ven.",
                "Nádech, zpevni břicho a posaď se mezi paty – kolena jdou ve směru špiček.",
                "V nejnižším bodě (stehna aspoň vodorovně, pokud to jde s rovnými zády) se vytlač nahoru."),
            listOf("Váha na celém chodidle.", "Hloubka jen do místa, kde zůstanou záda neutrální."),
            listOf("Kolena padají dovnitř.", "Paty se zvedají ze země.")),
        ex("leg_press", "Legpress", "Leg press", Equipment.MACHINE, 1,
            setOf(QUADS), setOf(GLUTES, HAMSTRINGS),
            listOf("m. quadriceps femoris"),
            listOf("m. gluteus maximus", "m. adductor magnus"),
            listOf("Sedni si, bedra i hýždě přitisknuté k opěrce, chodidla na šířku pánve uprostřed plošiny.",
                "Odjisti zátěž.",
                "Pomalu pokrč kolena k hrudníku, dokud se pánev nezačne zvedat.",
                "Vytlač zpět, kolena na konci nepropínej do zámku."),
            listOf("Níže položená chodidla = víc kvadriceps.", "Plný rozsah dle mobility."),
            listOf("Odlepení pánve od opěrky.", "Propnutí kolen do zámku.")),
        ex("leg_extension", "Předkopávání", "Leg extension", Equipment.MACHINE, 1,
            setOf(QUADS), emptySet(),
            listOf("m. rectus femoris", "m. vastus lateralis", "m. vastus medialis", "m. vastus intermedius"),
            emptyList(),
            listOf("Nastav osu stroje v úrovni kolen, opěrka nad kotníky.",
                "Chyť se madel.",
                "Propni kolena a nahoře zatni stehna.",
                "Pomalu zpět."),
            listOf("Jediný cvik, kde kvadriceps pracuje úplně izolovaně.", "Pomalé spouštění."),
            listOf("Švih.", "Zvedání hýždí ze sedáku.")),
        ex("walking_lunge", "Výpady v chůzi", "Walking lunge", Equipment.DUMBBELL, 1,
            setOf(QUADS, GLUTES), setOf(HAMSTRINGS, CALVES),
            listOf("m. quadriceps femoris", "m. gluteus maximus"),
            listOf("m. gluteus medius", "m. biceps femoris", "m. gastrocnemius"),
            listOf("Jednoručky podél těla, trup vzpřímený.",
                "Udělej dlouhý krok vpřed a spusť zadní koleno k zemi.",
                "Přední koleno nad kotníkem nebo mírně před ním.",
                "Vytlač se přední nohou a pokračuj dalším krokem."),
            listOf("Delší kroky víc zapojí hýždě.", "Pomalu a pod kontrolou."),
            listOf("Koleno padá dovnitř.", "Příliš krátké kroky.")),

        // ═══ HAMSTRINGY ═══
        ex("rdl", "Rumunský mrtvý tah", "Romanian deadlift", Equipment.BARBELL, 2,
            setOf(HAMSTRINGS, GLUTES), setOf(LOWER_BACK, FOREARMS),
            listOf("m. biceps femoris (caput longum)", "m. semitendinosus", "m. semimembranosus", "m. gluteus maximus"),
            listOf("m. erector spinae", "m. adductor magnus", "flexory prstů"),
            listOf("Stoj s osou v rukou, kolena lehce pokrčená.",
                "Posuň boky vzad a předkláněj se, osa klouže po stehnech.",
                "Jdi dolů, dokud cítíš silné protažení zadní strany stehen (obvykle pod koleny) a záda jsou rovná.",
                "Vytlač boky vpřed zpět do stoje."),
            listOf("Pohyb je ze zadku dozadu, ne z předklonu hrudníku.", "Úhel kolen se během pohybu nemění."),
            listOf("Kulatá záda.", "Pokrčení kolen do dřepu.")),
        ex("seated_leg_curl", "Zakopávání vsedě", "Seated leg curl", Equipment.MACHINE, 1,
            setOf(HAMSTRINGS), setOf(CALVES),
            listOf("m. semitendinosus", "m. semimembranosus", "m. biceps femoris"),
            listOf("m. gastrocnemius"),
            listOf("Sedni si, stehna zajisti horní opěrkou, spodní opěrka nad patami.",
                "Mírně se předkloň – protáhneš hamstringy.",
                "Ohni kolena co nejvíc pod sedák.",
                "Pomalu zpět."),
            listOf("Vsedě jsou hamstringy protažené u kyčle – roste víc než vleže (Maeo et al., 2021).", "Kontrolované spouštění."),
            listOf("Zvedání pánve.", "Krátký rozsah.")),
        ex("lying_leg_curl", "Zakopávání vleže", "Lying leg curl", Equipment.MACHINE, 1,
            setOf(HAMSTRINGS), setOf(CALVES),
            listOf("m. biceps femoris", "m. semitendinosus", "m. semimembranosus"),
            listOf("m. gastrocnemius"),
            listOf("Lehni si na břicho, opěrka nad patami, kolena těsně za hranou lavice.",
                "Drž se madel, boky přitisknuté.",
                "Přitáhni paty k hýždím.",
                "Pomalu zpět."),
            listOf("Pomalé spouštění buduje sílu.", "Špičky k sobě = víc lýtka, od sebe = méně."),
            listOf("Zvedání boků.", "Švih.")),
        ex("nordic_curl", "Nordický zdvih", "Nordic hamstring curl", Equipment.BODYWEIGHT, 3,
            setOf(HAMSTRINGS), emptySet(),
            listOf("m. biceps femoris", "m. semitendinosus", "m. semimembranosus"),
            listOf("m. gastrocnemius"),
            listOf("Klekni, paty zaklesni pod pevnou opěrku nebo ať ti je někdo drží.",
                "Tělo v přímce od kolen po hlavu.",
                "Pomalu se nakláněj vpřed a brzdi hamstringy co nejdéle.",
                "Zachyť se rukama a odraz zpět."),
            listOf("Prokazatelně snižuje riziko zranění hamstringů.", "Stačí 2–3 série po 3–6 opakováních."),
            listOf("Ohýbání v kyčlích.", "Pád bez brzdění.")),

        // ═══ LÝTKA ═══
        ex("standing_calf_raise", "Výpony vestoje", "Standing calf raise", Equipment.MACHINE, 1,
            setOf(CALVES), emptySet(),
            listOf("m. gastrocnemius"),
            listOf("m. soleus"),
            listOf("Postav se špičkami na vyvýšenou hranu, kolena propnutá.",
                "Spusť paty co nejníž do protažení.",
                "Vytlač se na špičky co nejvýš.",
                "Nahoře 1 s pauza, pomalu dolů."),
            listOf("Protažení dole je klíčové – lýtka rostou hlavně z plného rozsahu.", "Pauza dole zruší pružení šlach."),
            listOf("Pérování v malém rozsahu.", "Pokrčená kolena.")),
        ex("seated_calf_raise", "Výpony vsedě", "Seated calf raise", Equipment.MACHINE, 1,
            setOf(CALVES), emptySet(),
            listOf("m. soleus"),
            listOf("m. gastrocnemius"),
            listOf("Sedni si, opěrka na stehnech těsně nad koleny, špičky na hraně.",
                "Spusť paty do protažení.",
                "Vytlač se na špičky.",
                "Pomalu zpět."),
            listOf("Při pokrčeném koleni pracuje hlavně šíjový sval (soleus).", "Vyšší počty opakování."),
            listOf("Malý rozsah.", "Rychlé odrážení.")),

        // ═══ STROJE A KLADKY (šablony tréninků, docs/adr/0024) ═══
        ex("machine_chest_press", "Tlak na hrudním stroji", "Machine chest press", Equipment.MACHINE, 1,
            setOf(CHEST), setOf(FRONT_DELTS, TRICEPS),
            listOf("m. pectoralis major (pars sternocostalis)"),
            listOf("m. deltoideus (pars clavicularis)", "m. triceps brachii"),
            listOf("Nastav sedák tak, aby rukojeti byly ve výšce středu hrudníku.",
                "Záda a lopatky přitiskni do opěry, lopatky stáhni k sobě a dolů.",
                "S výdechem tlač rukojeti vpřed, lokty nepropínej do zámku.",
                "Pomalu vrať do protažení prsou, lokty asi 45–60° od těla."),
            listOf("Stroj vede dráhu – můžeš jít blíž k selhání bezpečněji než s osou.", "Pomalé spouštění (3 s) zvyšuje napětí při stejné váze."),
            listOf("Odlepování zad od opěry.", "Zkrácený rozsah dole.")),
        ex("incline_machine_press", "Šikmý tlak na stroji", "Incline machine press", Equipment.MACHINE, 1,
            setOf(CHEST), setOf(FRONT_DELTS, TRICEPS),
            listOf("m. pectoralis major (pars clavicularis)"),
            listOf("m. deltoideus (pars clavicularis)", "m. triceps brachii"),
            listOf("Sedák nastav tak, aby rukojeti vycházely z úrovně horního hrudníku.",
                "Lopatky stažené, hrudník nahoru, chodidla pevně na zemi.",
                "Tlač šikmo vzhůru, dokud nejsou paže skoro propnuté.",
                "Pomalu zpět do protažení horní části prsou."),
            listOf("Cílí na horní (klíčkovou) část prsního svalu.", "Úchop o něco užší než u rovného tlaku bývá pro ramena příjemnější."),
            listOf("Příliš vysoký sedák – z cviku se stane tlak na ramena.", "Zvedání ramen k uším.")),
        ex("pec_deck", "Peck deck (motýlek)", "Pec deck", Equipment.MACHINE, 1,
            setOf(CHEST), setOf(FRONT_DELTS),
            listOf("m. pectoralis major"),
            listOf("m. deltoideus (pars clavicularis)", "m. coracobrachialis"),
            listOf("Sedák nastav tak, aby rukojeti byly ve výšce ramen, lokty lehce pokrčené.",
                "Záda na opěře, lopatky stažené.",
                "Přitáhni paže obloukem před hrudník, na chvíli stiskni prsa.",
                "Pomalu zpět, dokud necítíš protažení – ne za rovinu ramen."),
            listOf("Izolace prsou bez tricepsu – hodí se na konec tréninku.", "Lokty drž ve stejném úhlu po celý pohyb."),
            listOf("Příliš velké zapažení – zátěž ramenního kloubu.", "Tlačení dlaněmi místo přitahování pažemi.")),
        ex("triceps_kickback", "Zapažování jednoručky na triceps", "Triceps kickback", Equipment.DUMBBELL, 1,
            setOf(TRICEPS), emptySet(),
            listOf("m. triceps brachii (caput laterale, caput longum)"),
            listOf("m. anconeus", "m. deltoideus (pars spinalis) – stabilizace"),
            listOf("Opři se rukou a kolenem o lavici, záda rovně, paže s jednoručkou podél těla.",
                "Nadloktí zvedni rovnoběžně s trupem a drž ho na místě.",
                "Propni loket vzad, nahoře krátce stiskni triceps.",
                "Pomalu pokrč zpět do pravého úhlu."),
            listOf("Lehká váha a čistá technika – páka je dlouhá.", "Nadloktí je osa pohybu, nesmí kývat."),
            listOf("Švih celou paží.", "Příliš těžká jednoručka a zkrácený rozsah.")),
        ex("machine_shoulder_press", "Tlak na ramena na stroji", "Machine shoulder press", Equipment.MACHINE, 1,
            setOf(FRONT_DELTS), setOf(TRICEPS, TRAPS),
            listOf("m. deltoideus (pars clavicularis, pars acromialis)"),
            listOf("m. triceps brachii", "m. trapezius (pars descendens)", "m. serratus anterior"),
            listOf("Sedák nastav tak, aby rukojeti začínaly ve výšce ramen.",
                "Záda opři, břicho zpevni.",
                "Tlač nahoru, dokud nejsou paže téměř propnuté.",
                "Pomalu spusť zpět do výšky ramen."),
            listOf("Bezpečná varianta tlaku nad hlavu pro těžké série.", "Neutrální úchop (dlaně k sobě) šetří ramena."),
            listOf("Prohnutí beder a odlepování od opěry.", "Spouštění jen do půlky.")),
        ex("cable_lateral_raise", "Upažování na kladce", "Cable lateral raise", Equipment.CABLE, 1,
            setOf(FRONT_DELTS), setOf(TRAPS),
            listOf("m. deltoideus (pars acromialis)"),
            listOf("m. supraspinatus", "m. trapezius (pars descendens)"),
            listOf("Postav se bokem ke spodní kladce, rukojeť drž vzdálenější rukou.",
                "Loket lehce pokrčený, trup vzpřímený.",
                "Upaž do výšky ramene, vedeno loktem.",
                "Pomalu zpět až k boku."),
            listOf("Kladka drží napětí i dole, kde jednoručka nepůsobí.", "Mírný úklon od kladky zvětší rozsah."),
            listOf("Krčení ramen místo upažení.", "Švih trupem.")),
        ex("machine_row", "Přítah na stroji s oporou hrudníku", "Chest-supported machine row", Equipment.MACHINE, 1,
            setOf(LATS, TRAPS), setOf(REAR_DELTS, BICEPS),
            listOf("m. latissimus dorsi", "m. trapezius (pars transversa)", "mm. rhomboidei"),
            listOf("m. deltoideus (pars spinalis)", "m. biceps brachii", "m. brachialis"),
            listOf("Hrudník opři o podložku, dosáhni na rukojeti v plném natažení.",
                "Nejdřív stáhni lopatky k sobě, pak táhni lokty dozadu.",
                "Na konci krátce podrž, lopatky u sebe.",
                "Pomalu natáhni paže a nech lopatky rozjet vpřed."),
            listOf("Opora hrudníku vypíná spodní záda – čistá práce zad.", "Široký úchop víc trapézy a zadní ramena, úzký víc široký zádový."),
            listOf("Odlepování hrudníku od opěry a trhání.", "Tahání jen rukama bez pohybu lopatek.")),
        ex("seated_cable_row", "Přítah spodní kladky vsedě", "Seated cable row", Equipment.CABLE, 1,
            setOf(LATS, TRAPS), setOf(REAR_DELTS, BICEPS, LOWER_BACK),
            listOf("m. latissimus dorsi", "m. trapezius (pars transversa)", "mm. rhomboidei"),
            listOf("m. deltoideus (pars spinalis)", "m. biceps brachii", "m. erector spinae (izometricky)"),
            listOf("Sedni si, chodidla na opěrky, kolena mírně pokrčená, záda rovně.",
                "Rukojeť (V-grip) přitáhni k pupku, lokty podél těla.",
                "Lopatky stáhni k sobě, hrudník vpřed.",
                "Pomalu natáhni paže, trup zůstává téměř vzpřímený."),
            listOf("Plný rozsah vpředu protáhne široký zádový.", "Trup se hýbe jen minimálně."),
            listOf("Velké houpání trupem.", "Kulatá záda v natažení.")),
        ex("preacher_curl", "Bicepsový zdvih na Scottově lavici", "Preacher curl", Equipment.MACHINE, 1,
            setOf(BICEPS), setOf(FOREARMS),
            listOf("m. biceps brachii (caput breve)", "m. brachialis"),
            listOf("m. brachioradialis", "mm. flexores carpi"),
            listOf("Nadloktí polož celou délkou na opěrku, podpaží na její horní hranu.",
                "Uchop osu (EZ) nebo rukojeti stroje podhmatem.",
                "Zvedni zátěž k ramenům, nadloktí zůstává na opěrce.",
                "Pomalu spusť skoro do propnutí – bez odrazu."),
            listOf("Opěrka zabrání švihu – čistá izolace bicepsu.", "Spodní část pohybu je nejtěžší – pomalu."),
            listOf("Propadnutí do úplného propnutí s těžkou vahou (zátěž šlachy).", "Zvedání loktů z opěrky.")),
        ex("hack_squat", "Hack dřep na stroji", "Hack squat", Equipment.MACHINE, 2,
            setOf(QUADS), setOf(GLUTES),
            listOf("m. quadriceps femoris"),
            listOf("m. gluteus maximus", "mm. adductores"),
            listOf("Záda a ramena opři o opěru, chodidla na platformu na šíři ramen.",
                "Odjisti a pomalu jdi do dřepu, kolena směřují nad špičky.",
                "Jdi co nejhlouběji s rovnými zády na opěře.",
                "Vytlač přes celé chodidlo nahoru, kolena nezamykej."),
            listOf("Chodidla níž = víc kvadriceps, výš = víc hýždě.", "Stroj dovolí bezpečně jít blízko selhání."),
            listOf("Odlepování pánve od opěry dole.", "Padání kolen dovnitř.")),
        ex("reverse_pec_deck", "Reverzní motýlek", "Reverse pec deck", Equipment.MACHINE, 1,
            setOf(REAR_DELTS), setOf(TRAPS),
            listOf("m. deltoideus (pars spinalis)"),
            listOf("m. infraspinatus", "m. teres minor", "m. trapezius (pars transversa)", "mm. rhomboidei"),
            listOf("Sedni si čelem k opěře, rukojeti ve výšce ramen.",
                "Paže téměř propnuté, lehce pokrčené lokty.",
                "Rozpaž obloukem dozadu do roviny těla.",
                "Pomalu zpět před tělo."),
            listOf("Vedeno loktem, ne rukama.", "Lehčí váha, více opakování (12–20)."),
            listOf("Stahování lopatek místo pohybu v rameni.", "Švih a zvedání ramen k uším."))
    )

    private val byId = ALL.associateBy { it.id }

    fun byId(id: String): Exercise? = byId[id]

    /** Cviky pro partii: nejdřív ty, kde je partie hlavní, pak vedlejší; v rámci skupiny podle obtížnosti. */
    fun forMuscle(m: Muscle): List<Exercise> =
        ALL.filter { m in it.primary }.sortedBy { it.level } + ALL.filter { m !in it.primary && m in it.secondary }.sortedBy { it.level }
}
